spring.datasource.url=jdbc:postgresql://localhost:5432/pdfapi
spring.datasource.username=pdfuser
spring.datasource.password=pdfpass
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.ssl.enabled=false
spring.rabbitmq.addresses=
